### ISSUE TITLE
HTTPSConnectionPool(host='jacketttt.herokuapp.com', port=443): Read timed out. (read timeout=10)

### ISSUE THREAD

**Issue by amogusballsw** [l3v11/Jackett-heroku#6]
HTTPSConnectionPool(host='jacketttt.herokuapp.com', port=443): Read timed out. (read timeout=10), is there a way to fix this? I have an bot running which is using 3 links per second, also great work.

**Comment by l3v11** [comment]
> HTTPSConnectionPool(host='jacketttt.herokuapp.com', port=443): Read timed out. (read timeout=10), is there a way to fix this? I have an bot running which is using 3 links per second, also great work.

Issue from jackett. Post it on their repo.
