### ISSUE TITLE
Flaresolverr error

### ISSUE THREAD

**Issue by sukhhdipsingh** [l3v11/Jackett-heroku#9]
error:
An error occurred while testing this indexer
Exception [website_name] : Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured
[Instructions to install and configure FlareSolverr.](https://github.com/Jackett/Jackett#configuring-flaresolverr)
[Troubleshooting frequent errors with FlareSolverr.](https://github.com/Jackett/Jackett/wiki/Troubleshooting#error-connecting-to-flaresolverr-server)

how can i configure flaresolverr on heroku?

**Comment by l3v11** [comment]
@DestinoLol 
Use a proxy site for the tracker which doesn't have cloudflare challenge
